"""
SiteVision AI - OSHA Incident & Safety Audit PDF Report Generator
Generates clean, professional construction safety reports with worker identification.
"""

from fpdf import FPDF
import datetime
import tempfile
import os
from PIL import Image


class SafetyReportPDF(FPDF):
    """Clean, single-page OSHA-compliant safety audit PDF document."""
    def header(self):
        self.set_fill_color(18, 18, 24)
        self.rect(0, 0, 210, 24, 'F')
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "SITEVISION AI // OSHA COMPLIANCE & INCIDENT AUDIT REPORT", align="C", ln=True)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(160, 160, 170)
        self.cell(0, 4, "Autonomous Computer Vision PPE & DLP Access Control Governance", align="C", ln=True)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by SiteVision AI | Verified per OSHA Standard 1926", align="C")


def create_osha_pdf(telemetry: dict, llm_report_text: str, image_pil: Image.Image, worker_profile: dict = None) -> bytes:
    """
    Generates a PDF audit report in memory and safely returns PDF bytes for download.
    """
    pdf = SafetyReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    status = telemetry.get("status", "SAFE")
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    w_name = worker_profile.get("name", "Registered Personnel") if worker_profile else "Registered Personnel"
    w_id = worker_profile.get("id", "WRK-8901") if worker_profile else "WRK-8901"
    w_role = worker_profile.get("role", "Site Engineer") if worker_profile else "Site Engineer"
    w_dept = worker_profile.get("department", "Operations") if worker_profile else "Operations"
    w_zone = worker_profile.get("zone", "Sector 4") if worker_profile else "Sector 4"

    # 1. Incident Status Banner
    if status == "BLOCKED":
        pdf.set_fill_color(220, 38, 38) # Red
        status_title = f"CRITICAL VIOLATION: ID {w_id} SUSPENDED (DLP RULE)"
    elif status == "WARNING":
        pdf.set_fill_color(217, 119, 6) # Amber
        status_title = f"WARNING: PPE NON-COMPLIANCE DETECTED FOR {w_name.upper()}"
    else:
        pdf.set_fill_color(16, 185, 129) # Green
        status_title = f"CLEARANCE APPROVED: {w_name.upper()} CLEARED FOR ENTRY"

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 9, f"  {status_title}", fill=True, ln=True)
    pdf.ln(4)

    # 2. Worker Identification Metadata Grid
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(30, 30, 40)
    pdf.cell(50, 6, f"Personnel: {w_name}", border=1)
    pdf.cell(45, 6, f"Worker ID: {w_id}", border=1)
    pdf.cell(50, 6, f"Designation: {w_role}", border=1)
    pdf.cell(45, 6, f"Clearance: {status}", border=1, ln=True)

    pdf.set_font("Helvetica", "", 8.5)
    pdf.cell(50, 6, f"Dept: {w_dept}", border=1)
    pdf.cell(45, 6, f"Zone: {w_zone}", border=1)
    pdf.cell(50, 6, f"Audit Time: {timestamp}", border=1)
    pdf.cell(45, 6, f"Gate Action: {'LOCKED' if status == 'BLOCKED' else ('HOLD' if status == 'WARNING' else 'OPEN')}", border=1, ln=True)
    pdf.ln(4)

    # 3. PPE Inspection Table
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(20, 20, 30)
    pdf.cell(0, 6, "1. Real-Time Vision & PPE Telemetry Breakdown", ln=True)
    
    pdf.set_font("Helvetica", "", 9)
    # Table Header
    pdf.set_fill_color(240, 240, 245)
    pdf.cell(60, 6, "Safety Item", border=1, fill=True)
    pdf.cell(40, 6, "Detected State", border=1, fill=True)
    pdf.cell(40, 6, "Confidence", border=1, fill=True)
    pdf.cell(50, 6, "OSHA Compliance Action", border=1, fill=True, ln=True)

    # Rows
    h_ok = telemetry.get("helmet", False)
    v_ok = telemetry.get("vest", False)
    s_bad = telemetry.get("smoking", False)

    pdf.cell(60, 6, "Hardhat / Cranial Gear", border=1)
    pdf.cell(40, 6, "COMPLIANT" if h_ok else "MISSING", border=1)
    pdf.cell(40, 6, f"{int(telemetry.get('helmet_conf', 0)*100)}%", border=1)
    pdf.cell(50, 6, "Cleared" if h_ok else "Mandatory Equip", border=1, ln=True)

    pdf.cell(60, 6, "High-Vis Reflective Vest", border=1)
    pdf.cell(40, 6, "COMPLIANT" if v_ok else "MISSING", border=1)
    pdf.cell(40, 6, f"{int(telemetry.get('vest_conf', 0)*100)}%", border=1)
    pdf.cell(50, 6, "Cleared" if v_ok else "Mandatory Equip", border=1, ln=True)

    pdf.cell(60, 6, "Contraband / Smoking (DLP)", border=1)
    pdf.cell(40, 6, "HAZARD DETECTED" if s_bad else "NONE (CLEAR)", border=1)
    pdf.cell(40, 6, f"{int(telemetry.get('smoking_conf', 0)*100)}%", border=1)
    pdf.cell(50, 6, "IMMEDIATE ID SUSPENSION" if s_bad else "Cleared", border=1, ln=True)

    pdf.ln(4)

    # 4. Embedded Detection Image
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "2. Visual Evidence Capture (Real-Time HUD Overlay)", ln=True)
    
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        tmp_path = tmp.name
        img_copy = image_pil.copy()
        img_copy.thumbnail((700, 700))
        img_copy.save(tmp_path, "JPEG")

    try:
        pdf.image(tmp_path, x=45, y=pdf.get_y() + 2, w=120)
        pdf.set_y(pdf.get_y() + 80)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    # 5. AI Safety Officer Assessment
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(20, 20, 30)
    pdf.cell(0, 6, "3. AI Safety Officer Formal Assessment", ln=True)
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 60)
    clean_report = llm_report_text.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 5, clean_report, border=1)
    
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 110)
    pdf.cell(0, 4, f"Digital Audit Signed: SiteVision AI Engine | Worker: {w_name} ({w_id}) | OSHA Standard 1926.151 / 1926.100", align="R")

    # Safe output conversion across all fpdf / fpdf2 versions
    raw_out = pdf.output()
    if isinstance(raw_out, (bytes, bytearray)):
        return bytes(raw_out)
    elif isinstance(raw_out, str):
        return raw_out.encode("latin-1")
    else:
        return bytes(raw_out)
